config/routes.rb
Rails.application.routes.draw do
  root 'tourbases#my_tourbase'

  devise_for :users, controllers: { registrations: 'users/registrations'}

  resources :tourbases
  resources :regions
  resources :tourists
  resources :users
  resources :tours

  get :random_cat, controller: 'cats'
  get :my_tourbase, controller: 'tourbases'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :tourbases, class_name: 'Tourbase', dependent: :destroy

  validates_presence_of :nearest_city, :country, :country_code
end

app/models/token.rb
class Token < ApplicationRecord
end

app/models/tour.rb
class Tour < ApplicationRecord
  belongs_to :tourist
  belongs_to :tourbase

  validates_presence_of :tour_starts, :tour_duration_days, :tour_finishes, :tourist
  validates :tour_duration_days, numericality: { :greater_than_or_equal_to => 3 }
  before_validation :count_tour_finishes
  validate :validate_dates

  def count_tour_finishes
    self.tour_finishes = tour_starts + tour_duration_days.days
  end

  def validate_dates
    errors.add(:tour_starts, 'should be today or later') if tour_starts < Date.today
  end
end

app/models/tourbase.rb
class Tourbase < ApplicationRecord
  belongs_to :region
  has_many :tourists, dependent: :nullify
  has_many :tours, dependent: :destroy
  has_many :users, dependent: :restrict_with_error

  validates_presence_of :region, :name, :max_capacity
  validates :current_capacity, numericality: { :greater_than_or_equal_to => 0 }
  before_validation :count_current_capacity

  def count_current_capacity
    self.current_capacity = max_capacity - tours.count
  end
end

app/models/tourist.rb
class Tourist < ApplicationRecord
  has_one :tour, dependent: :destroy

  validates_presence_of :firstname, :lastname, :age, :email
  validates :age, numericality: { :greater_than_or_equal_to => 14 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :tourbase
  validate :validate_token

  def is_admin?
    is_admin
  end

  def validate_token
    return if token_id.start_with?('us') || token_id.start_with?('ad')

    errors.add(:token_id, 'not registered in system')
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  EDIT_METHODS = %w[POST PUT PATCH DELETE].freeze

  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:firstname, :lastname, :email, :password, :password_confirmation, :token_id)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:firstname, :lastname, :email, :password, :current_password)
    end
  end

  def is_elder?
    head :forbidden unless current_user.is_admin?
  end

end

app/controllers/cats_controller.rb
# frozen_string_literal: true

class CatsController < ApplicationController
  def random_cat
    @cat = Cats::GetRandomCat.meow
  end
end

app/controllers/regions_controller.rb
# frozen_string_literal: true

class RegionsController < ApplicationController
  before_action :is_elder?, except: :index
  before_action :region, only: %i[edit update destroy]

  def index
    @regions = Region.all
    @new_region = Region.new
  end

  def create
    @region = Region.create(region_params)
  end

  def edit; end

  def update
    @new_region = Region.new
    @region.update(region_params)
  end

  def destroy
    @region.destroy
  end

  private

  def region_params
    params.require(:region).permit(:nearest_city, :country, :country_code)
  end

  def region
    @region = Region.find(params[:id])
  end
end

app/controllers/tourbases_controller.rb
# frozen_string_literal: true

class TourbasesController < ApplicationController
  before_action :is_elder?, except: [:index, :my_tourbase]
  before_action :tourbase, only: %i[edit update destroy show]

  def index
    @new_tourbase = Tourbase.new
    @tourbases = Tourbase.all.preload(:tours)
  end

  def create
    @tourbase = Tourbase.create(tourbase_params)
  end

  def show
    @tours = @tourbase.tours
  end

  def edit; end

  def update
    @new_tourbase = Tourbase.new
    @tourbase.update(tourbase_params)
  end

  def destroy
    @tourbase.destroy
  end

  def my_tourbase
    @tourbase = current_user.tourbase
    @new_tour = Tour.new
  end

  private

  def tourbase_params
    params.require(:tourbase).permit(:name, :region_id, :max_capacity)
  end

  def tourbase
    @tourbase = Tourbase.find(params[:id])
  end
end

app/controllers/tourists_controller.rb
# frozen_string_literal: true

class TouristsController < ApplicationController
  before_action :is_elder?, except: :index
  before_action :tourist, only: %i[edit update destroy]

  def index
    @new_tourist = Tourist.new
    @tourists = Tourist.all
  end

  def create
    @tourist = Tourist.create(tourist_params)
  end

  def edit; end

  def update
    @new_tourist = Tourist.new
    @tourist.update(tourist_params)
  end

  def destroy
    @tourist.destroy
  end

  private

  def tourist_params
    params.require(:tourist).permit(:firstname, :lastname, :age, :email)
  end

  def tourist
    @tourist = Tourist.find(params[:id])
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :tour, only: %i[edit update destroy]

  def index
    @new_tour = Tour.new
    @tours = Tour.all
  end

  def create
    @tour = Tour.create(tour_params)
    Tourist.find(@tour.tourist_id).update(tour_id: @tour.id) if @tour.valid?
  end

  def edit; end

  def update
    @new_tour = Tour.new
    @tour.update(tour_params)
    Tourist.find(@tour.tourist_id).update(tour_id: @tour.id) if @tour.valid?
  end

  def destroy
    @tour.destroy
    Tourist.find(@tour.tourist_id).update(tour_id: nil)
  end

  private

  def tour_params
    params.require(:tour).permit(:tour_starts, :tourist_id, :tour_duration_days, :tourbase_id)
  end

  def tour
    @tour = Tour.find(params[:id])
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]

  def create
    create_params = sign_up_params
    create_params[:is_admin] = true if create_params[:token_id].start_with?('ad')
    create_params[:tourbase_id] = Tourbase.last.id

    build_resource(create_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end


  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:firstname, :lastname, :email, :password, :password_confirmation, :token_id) }
    devise_parameter_sanitizer.permit(:token_id)
  end

end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :is_elder?

  def index
    @users = User.all
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def for_elder_only
    current_user.is_admin? ? yield : nil
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tourbases DB</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'img_1.png', type: 'image/png' %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= render 'shared/nav' %>
    <% end %>
    <% if notice %> <p class="alert alert-success"><%= notice %></p> <% end %>
    <% if alert %> <p class="alert alert-error"><%= alert %></p> <% end %>

    <%= yield %>
    <%= render 'shared/footer' %>
  </body>


</html>

app/views/regions/_form.haml
%div.container-md.region-form
  %h4= "#{action} Region"
  = form_for region, remote: true do |f|
    %div.row
      %div.mb-3.col
        = f.label :nearest_city, class: 'form-label'
        = f.text_field :nearest_city, class: 'form-control'
      %div.mb-3.col
        = f.label :country, class: 'form-label'
        = f.text_field :country, class: 'form-control'
      %div.mb-3.col
        = f.label :country_code, class: 'form-label'
        = f.text_field :country_code, class: 'form-control'
      %div.mb-3
        = f.submit action, class: "btn btn-primary"

app/views/regions/_region.haml
%tr[region]
  %td= region.nearest_city
  %td= region.country
  %td= region.country_code
  - for_elder_only do
    %td
      = link_to "Edit", edit_region_path(region), remote: true
      = link_to "Destroy", region_path(region), method: :delete, remote: true, data: { confirm: "Are you sure?" }

app/views/regions/create.js.erb
<% if @region.valid? %>
  $('.add-regions-errors').html('')
  $('.regions-table').append('<%=j render partial: 'region', locals: { region: @region }%>')
  $('.form-control').each(function(index) {
      this.value = ""
  })
<% else %>
  $('.add-regions-errors').html('<%=j render partial: 'shared/errors_list', locals: { errors: @region.errors }%>')
<%end%>

app/views/regions/destroy.js.erb
$('#region_<%=@region.id%>').remove();

app/views/regions/edit.js.erb
$('.region-form')[0].innerHTML = '<%=j render partial: 'form', locals: { region: @region, action: 'Update' }%>'

app/views/regions/index.haml
%h2.display-5 Regions

.add-regions-errors

- for_elder_only do
  = render partial: 'form', locals: {region: @new_region, action: 'Create'}

%table.table.table-striped.table-info.table-hover.regions-table
  %th Nearest city
  %th Country
  %th Country code
  - for_elder_only do
    %th Actions
  = render @regions

app/views/regions/update.js.erb
<% if @region.valid? %>
  $('.add-regions-errors').html('')
  $('#region_<%=@region.id%>')[0].innerHTML = '<%=j render partial: 'region', locals: { region: @region }%>'
  $('.form-control').each(function(index) {
      this.value = ""
  })
  $('.region-form')[0].innerHTML = '<%=j render partial: 'form', locals: {region: @new_region, action: 'Create'}%>'
<% else %>
  $('.add-regions-errors').html('<%=j render partial: 'shared/errors_list', locals: { errors: @region.errors }%>')
<%end%>

app/views/shared/_errors_list.html.haml
%div.container-md.alert.alert-danger
  - errors.full_messages.each do |msg|
    %p= msg

app/views/shared/_footer.haml
%footer.text-center.text-lg-start.bg-light.text-muted{style: "position:absolute; bottom:0; height: 70px; width:100%;"}
  %section.d-flex.justify-content-center.justify-content-lg-between.p-4.border-bottom
    %div.me-5.d-none.d-lg-block
      Application for convenient tourbase management

  %div.text-center.p-4{style: "background-color: rgba(0, 0, 0, 0.05);"}
    © 2021 Made by phantom-profile as REU project

app/views/shared/_nav.haml
%nav.navbar.navbar-expand.bg-light
  %p.d-inline-block.align-top= image_tag 'img_1.png', size: "30x30"
  %p= link_to 'Tourbases DB', root_path, class: "navbar-brand"

  %div.collapse.navbar-collapse{id: "navbarSupportedContent"}
    %ul.navbar-nav.mr-auto
      %li.nav-item.active
        %p= link_to "My tourbase", my_tourbase_path, class: "nav-link"
      %li.nav-item.active
        %p= link_to "Regions", regions_path, class: "nav-link"
      - for_elder_only do
        %li.nav-item.active
          %p= link_to "Tourbases", tourbases_path, class: "nav-link"
        %li.nav-item
          %p= link_to "Tourists", tourists_path, class: "nav-link"
        %li.nav-item
          %p= link_to "Users", users_path, class: "nav-link"
      %li.nav-item
        %p= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link"

app/views/tourbases/_form.haml
%div.container-md.tourbase-form
  %h4= "#{action} Tourbase"
  = form_for tourbase, remote: true do |f|
    %div.row
      %div.mb-3.col
        = f.label :name, class: 'form-label'
        = f.text_field :name, class: 'form-control'
      %div.mb-3.col
        = f.label :region, class: 'form-label'
        = f.select :region_id, Region.all.collect { |r| [r.nearest_city, r.id] }, {}, class: 'form-select'
      %div.mb-3.col
        = f.label :max_capacity, class: 'form-label'
        = f.number_field :max_capacity, class: "form-control", id: "replyNumber", min: "1", step: "1", "data-bind": "value:replyNumber"
      %div.mb-3
        = f.submit action, class: "btn btn-primary"

app/views/tourbases/_tourbase.haml
%tr[tourbase]
  %td= tourbase.name
  %td= tourbase.region.nearest_city
  %td= tourbase.current_capacity
  %td= tourbase.tours.size
  %td= render partial: 'weather', locals: { weather: Weather::GetCurrentWeather.new(tourbase).call }
  - for_elder_only do
    %td
      = link_to "Edit", edit_tourbasis_path(tourbase), remote: true
      = link_to "Destroy", tourbasis_path(tourbase), method: :delete, remote: true, data: { confirm: "Are you sure?" }

app/views/tourbases/_weather.haml
%div.weather-icon
  %div
    ="#{weather[:temp]} °C, #{weather[:wind_speed]} m/sec"
    %img{src: "http://openweathermap.org/img/w/#{weather[:icon]}.png"}

app/views/tourbases/create.js.erb
<% if @tourbase.valid? %>
  $('.add-school-errors').html('')
  $('.tourbases-table').append('<%=j render partial: 'tourbase', locals: { tourbase: @tourbase }%>')
  $('.form-control').each(function(index) {
    this.value = ""
  })
<% else %>
  $('.add-tourbase-errors').html('<%=j render partial: 'shared/errors_list', locals: { errors: @tourbase.errors }%>')
<%end%>

app/views/tourbases/destroy.js.erb
$('#tourbase_<%=@tourbase.id%>').remove();

app/views/tourbases/edit.js.erb
$('.tourbase-form')[0].innerHTML = '<%=j render partial: 'form', locals: { tourbase: @tourbase, action: 'Update' }%>'

app/views/tourbases/index.haml
%h2.display-5 Tourbases

.add-tourbase-errors

- for_elder_only do
  = render partial: 'form', locals: {tourbase: @new_tourbase, action: 'Create' }

%table.table.table-striped.table-info.table-hover.tourbases-table
  %th Name
  %th Region
  %th Current capacity
  %th Members
  %th Current weather
  - for_elder_only do
    %th Actions
  = render @tourbases

app/views/tourbases/my_tourbase.haml
%h2.display-5= "Tourists on my tourbase #{@tourbase.name} in #{@tourbase.region.nearest_city}"
%h3= render partial: 'weather', locals: {weather: Weather::GetCurrentWeather.new(@tourbase).call}
.add-tours-errors

= render partial: 'tours/form', locals: {tour: @new_tour, action: 'Create'}

%table.table.table-striped.table-info.table-hover.tours-table
  %th Firstname
  %th Lastname
  %th Age
  %th Email
  %th Tour started
  %th Tour finishes
  %th Actions
  = render @tourbase.tours

app/views/tourbases/update.js.erb
<% if @tourbase.valid? %>
  $('.add-tourbase-errors').html('')
  $('#tourbase_<%=@tourbase.id%>')[0].innerHTML = '<%=j render partial: 'tourbase', locals: { tourbase: @tourbase }%>'
  $('.form-control').each(function(index) {
      this.value = ""
  })
  $('.tourbase-form')[0].innerHTML = '<%=j render partial: 'form', locals: { tourbase: @new_tourbase, action: 'Create' }%>'
<% else %>
  $('.add-tourbase-errors').html('<%=j render partial: 'shared/errors_list', locals: { errors: @tourbase.errors }%>')
<%end%>

app/views/tourists/_form.haml
%div.container-md.tourist-form
  %h4= "Add Tourist"
  = form_for tourist, remote: true do |f|
    %div.row
      %div.mb-3.col
        = f.label :firstname, class: 'form-label'
        = f.text_field :firstname, class: 'form-control'
      %div.mb-3.col
        = f.label :lastname, class: 'form-label'
        = f.text_field :lastname, class: 'form-control'
    %div.row
      %div.mb-3.col
        = f.label :age, class: 'form-label'
        = f.number_field :age, class: "form-control", id: "replyNumber", min: "14", step: "1", "data-bind": "value:replyNumber"
      %div.mb-3.col
        = f.label :email, class: 'form-label'
        = f.text_field :email, class: 'form-control'
    %div.row
      %div.mb-3
        = f.submit action, class: "btn btn-primary"

app/views/tourists/_tourist.haml
%tr[tourist]
  %td= tourist.firstname
  %td= tourist.lastname
  %td= tourist.age
  %td= tourist.email
  %td= tourist.tour.nil? ? 'No' : 'Yes'
  - for_elder_only do
    %td
      = link_to "Edit", edit_tourist_path(tourist), remote: true
      = link_to "Destroy", tourist_path(tourist), method: :delete, remote: true, data: { confirm: "Are you sure?" }

app/views/tourists/create.js.erb
<% if @tourist.valid? %>
  $('.add-tourists-errors').html('')
  $('.tourists-table').append('<%=j render partial: 'tourist', locals: { tourist: @tourist }%>')
  $('.form-control').each(function(index) {
      this.value = ""
  })
<% else %>
  $('.add-tourists-errors').html('<%=j render partial: 'shared/errors_list', locals: { errors: @tourist.errors }%>')
<%end%>

app/views/tourists/destroy.js.erb
$('#tourist_<%=@tourist.id%>').remove();

app/views/tourists/edit.js.erb
$('.tourist-form')[0].innerHTML = '<%=j render partial: 'form', locals: { tourist: @tourist, action: 'Update' }%>'

app/views/tourists/index.haml
%h2.display-5 Tourists

.add-tourists-errors

- for_elder_only do
  = render partial: 'form', locals: {tourist: @new_tourist, action: 'Create'}

%table.table.table-striped.table-info.table-hover.tourists-table
  %th Firstname
  %th Lastname
  %th Age
  %th Email
  %th Currently on tour

  - for_elder_only do
    %th Actions
  = render @tourists

app/views/tourists/update.js.erb
<% if @tourist.valid? %>
  $('.add-tourists-errors').html('')
  $('#tourist_<%=@tourist.id%>')[0].innerHTML = '<%=j render partial: 'tourist', locals: { tourist: @tourist }%>'
  $('.form-control').each(function(index) {
      this.value = ""
  })
  $('.tourist-form')[0].innerHTML = '<%=j render partial: 'form', locals: {tourist: @new_tourist, action: 'Create'}%>'
<% else %>
  $('.add-tourists-errors').html('<%=j render partial: 'shared/errors_list', locals: { errors: @tourist.errors }%>')
<%end%>

app/views/tours/_form.haml
%div.container-md.tour-form
  %h4= "#{action} Tour"
  = form_for tour, remote: true do |f|
    %div.row
      %div.mb-3.col
        = f.label :tour_duration_days, class: 'form-label'
        = f.number_field :tour_duration_days, class: "form-control", id: "replyNumber", min: "3", step: "1", "data-bind": "value:replyNumber"
      %div.mb-3.col
        = f.label :tour_starts, class: 'form-label'
        = f.date_field :tour_starts, class: 'form-control'
    %div.row
      %div.mb-3.col
        = f.label :tourist, class: 'form-label'
        = f.select :tourist_id, Tourist.where(tour_id: nil).collect { |t| ["#{t.email} - #{t.firstname} #{t.lastname}", t.id] }, {}, class: 'form-select'
        = f.hidden_field :tourbase_id, value: current_user.tourbase.id
      %div.mb-3
        = f.submit action, class: "btn btn-primary"

app/views/tours/_tour.haml
%tr[tour]
  %td= tour.tourist.firstname
  %td= tour.tourist.lastname
  %td= tour.tourist.age
  %td= tour.tourist.email
  %td= tour.tour_starts
  %td= tour.tour_finishes

  %td
    = link_to "Finished and accepted", tour_path(tour), method: :delete, remote: true, data: { confirm: "All tour finishing operations completed?" }

app/views/tours/create.js.erb
<% if @tour.valid? %>
  $('.add-tours-errors').html('')
  $('.tours-table').append('<%=j render partial: 'tour', locals: { tour: @tour }%>')
  $('.form-control').each(function(index) {
      this.value = ""
  })
  $("#tour_tourist_id").children('[value=<%= @tour.tourist.id %>]').remove();
<% else %>
  $('.add-tours-errors').html('<%=j render partial: 'shared/errors_list', locals: { errors: @tour.errors }%>')
<%end%>

app/views/tours/destroy.js.erb
$('#tour_<%=@tour.id%>').remove();

var newLi = document.createElement('option')
newLi.setAttribute('value', '<%= @tour.tourist.id %>')
newLi.text = '<%= @tour.tourist.email %> - <%= @tour.tourist.firstname + ' ' + @tour.tourist.lastname %>'
$("#tour_tourist_id")[0].appendChild(newLi)

app/views/tours/edit.js.erb
$('.tour-form')[0].innerHTML = '<%=j render partial: 'form', locals: { tour: @tour, action: 'Update' }%>'

app/views/tours/index.haml
%h2.display-5 Witchers

.add-witchers-errors

- for_elder_only do
  = render partial: 'form', locals: {witcher: @new_witcher, action: 'Create'}

%table.table.table-striped.table-info.table-hover.witchers-table
  %th Name
  %th Nickname
  %th Age
  %th Currently located
  %th School
  %th Sword
  - for_elder_only do
    %th Actions
  = render @witchers

app/views/tours/random_cat.haml
%div.container-md
  %p= image_tag(@cat, size: "1200x750")
  = button_to 'One more!', random_cat_path, method: :get, class: 'btn btn-primary primary-button'

app/views/tours/update.js.erb
<% if @tour.valid? %>
  $('.add-tours-errors').html('')
  $('#tour_<%=@tour.id%>')[0].innerHTML = '<%=j render partial: 'tour', locals: { tour: @tour }%>'
  $('.form-control').each(function(index) {
      this.value = ""
  })
  $('.tour-form')[0].innerHTML = '<%=j render partial: 'form', locals: {tour: @new_tour, action: 'Create'}%>'
<% else %>
  $('.add-tours-errors').html('<%=j render partial: 'shared/errors_list', locals: { errors: @tour.errors }%>')
<%end%>

app/views/users/_user.haml
%tr[user]
  %td= user.firstname
  %td= user.lastname
  %td= user.email
  %td= user.is_admin?
  %td= user.created_at
  %td
    = link_to_unless user.is_admin?, "Destroy", user_path(user), method: :delete,
      remote: true,
      data: { confirm: "Are you sure?" }

app/views/users/destroy.js.erb
$('#user_<%=@user.id%>').remove();

app/views/users/index.haml
%h2.display-5 Users

%table.table.table-striped.table-info.table-hover.users-table
  %th Firstname
  %th Lastname
  %th Email
  %th Is Admin
  %th Account created
  %th Actions
  = render @users